name: jollycast
description: "Jolcast - A modern podcast streaming application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  just_audio: ^0.10.5
  flutter_svg: ^2.2.3
  video_player: ^2.8.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/jollyIcon.svg
    - assets/icons/
    - assets/mp4/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/Jolly2.png"
  adaptive_icon_background: "#003334"
  adaptive_icon_foreground: "assets/icons/Jolly2.png"
